version: '3.3'

services:
  registry:
    image: localhost:5000/govrnanza.registry.webapi:dev
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - CONFIGURATION_FILE=/registry-config
      - REGISTRY_DB_PASSWORD_SECRET_FILE=/run/secrets/registry_db_password
    ports:
      - "31000:80"
    networks:
      - web
    secrets:
      - registry_db_password
    configs:
      - registry-config

secrets:
  registry_db_password:
    file: ./secrets/registryDbPassword.txt

configs:
  registry-config:
    file: ./configs/registryAppSettings.json

networks:
  web: